export const API_URL = "https://giro-api.onrender.com"

export const carColors = [
    "White",
    "Black",
    "Gray",
    "Silver",
    "Blue",
    "Red",
    "Brown",
    "Green",
    "Yellow",
    "Gold",
    "Orange",
    "Beige",
    "Burgundy",
    "Purple",
    "Pink",
    "Teal",
    "Turquoise",
    "Copper",
    "Maroon",
    "Charcoal",
    "Navy Blue",
    "Ivory",
    "Champagne",
    "Lime Green",
    "Mint Green"
];

export const carManufacturers = [
    "Acura",
    "Alfa Romeo",
    "Audi",
    "Bentley",
    "BMW",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "GMC",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Maserati",
    "Mazda",
    "Mercedes-Benz",
    "Mitsubishi",
    "Nissan",
    "Porsche",
    "Ram",
    "Subaru",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo"
];

